{% set version = "0.1.3" %}

package:
    name: dxchange
    version: {{ version }}

source:
    url: https://github.com/data-exchange/dxchange/archive/v{{ version }}.tar.gz
    fn: dxchange-{{ version }}.tar.gz
    sha256: 252be2283878384b59a23482eab870f51d63b9205d34e26e4f319d2bced90519

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - dxfile
        - edffile
        - h5py
        - netcdf4
        - numpy
        - python
        - six
        - spefile
        - tifffile

test:
    imports:
        - dxchange
        - dxchange.reader
        - dxchange.writer
        - dxchange.exchange

about:
    home: http://dxchange.readthedocs.org
    license: BSD 3-Clause
    summary: 'Data I/O for tomography.'

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - ericdill
        - licode
        - ravescovi
        - tacaswell
