{% set version = "0.1.7" %}

package:
  name: dxchange
  version: {{ version }}

source:
  url: https://github.com/data-exchange/dxchange/archive/v{{ version }}.tar.gz
  sha256: 8ce7c1ce3bdb483f285ba7483657691907e93c57c85067fe7bfa5756c2fc429f

build:
  number: 0
  noarch: python >=3.6
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python
    - dxfile
    - edffile
    - h5py
    - netcdf4
    - numpy
    - scipy
    - six
    - spefile
    - tifffile
    - pandas
    
test:
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data I/O for tomography

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
