travis:
  secure:
    BINSTAR_TOKEN: AB3fARD4ZsucfPWdOGtZEDs3rieV26l5R5lmtY+/eHEe76IepSr7h6IWLjJbzynYaGIn8lUD+eHZtLaPi1T8l8RR0S+oew8AGSRp7v0IfQDpfpdp+7LrpFFe2/hl1ZD+2wNsD9zuNPlgLwQYMkxfwhrJgw6H6tbeFQgnOMQb8yvmZ2q5E8rSt83asXbCHwRRtPezYGlIuTqOXiC6pZHXb4j4d/4PkzVv4Coufv5ACH8xR06l2Pv4nH2hz9dIYbgfJI6BKUvZ8jMk0p7aCQhEXC2qw+lAbequdLbmrK5dqbGhptYHOTSODUQEVQmMq0E7ZYp3pA0DtosfaJUukNHs1F8xO8cdBq1vGs9baukaFbFVtm6WQseImVa1Zna438Jd0C/fhJE+CJAha7ZIq1PZJPQ3EXofUixiZ5NMGjV7UfSjFci6KqOn1PhCyUpgkZb+IbVhLEUlnC3oj1+ViddPwE+5zzHuz3/VZqLRVKmk04GBBP/1etWsGivj74o+LQETuaUSVkDJF9Of5PyHvi2jOSnmJdvtUhILjmZemI6AGmC7j2Q7+rHLwMzfprH5kDl7nUZkLcXBzDqSHKjaXU7T3aZuaIZ6vvNaJHkwUfvOBebwbSl0yTAyaVlhiyn+PW3FqnYGCYNowX2ojbwe1wr2Zv6gDXk1rgs71EYr3U1932k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
