appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DTkc+8v0zH9IkZfkaTtBSdFfM4FSqaAPHlcW1tN1xK+/xaBOimFt5vOtEyMJcE5KxWTUttnNWUhff3SnEKdEoLtKJodGoCfuNfvKipyanSSOpt6hXLXVjbHoh8Nnvxw65j8L+66fT3gNe2NAgxSdAqSv3dJQHvlDYL6OOiGgI71zAwbGOzQvapkU43HhD6Rnnwugpsbx7JBKA6oXPpyy1J3TM8ENo6bMS8HvI7N9utxa6++nWa8EduttfkBzb5CPvFpPqKf4S8uxtTEiEFnyve+ZKYljTUp57JdL2U1vv5Ud79mJ3ribcwAPCW1CPP3/mwPTanjRWa7VQzgwQP+SK0qHHxyD3W6UJrjtMfbeJ0YLDFObvqanndl/8VzsT+fzm5d2mgaePbiSczkn3LFfVEAft7VF4jgmJjDEOlx7ZXOhnR9rEmwBzupPCP0PjTDABV0/Xy9RgzaQihQgp3nLlfzoxA9Pv2bNBVUeRSM/mDE7lnVC+rB5gswDKqhDQYnQmaptmS1aEm3na2pLFu8zlOxcMYNay2kUAj+4x/qoyD6AJJZnN+zFVfK0RzMB0ULQfX+a9ZeIpbx4FOs1eUkX1wB1RK5qnxNeTaOruY9WDnYBTzqgvWpqmhjO1hMjcqTgCw0Euiz55MPMqPhv5TPy+hU8DzLvJ+Tic0whFuNB7G0=}
