travis:
  secure:
    BINSTAR_TOKEN: nOEQDHc1jZqkQVPYBb1LjMW4Yv6IKCLpdPktRjTkkeP3UWtYaBJPgkAR6dodR2Epmj8FU2dOKr0qAPDaEHosqb2/7IiQas1IVS6z0IRCvkoJZ/iZSjfpT/eKZpGoetAS8zKE46H92sI1RqESiF1J1c3DXYD57MIBJUntZOjwLtgSFng5/t7eRJeND2XU3ggn4V2bYOt6EE1WWHEbCQOKIISbvPS+V7OKFQSG3PweQ0E+oh6FaeNcKninSOUTgPmdoz0i/YFgMf2rlTIgTUKvO32StknPvJdmVkTcHqv68Wa7ZFa6a5wVRhx3O/FxFT7nkgAhC1LknBbNSMAv+gY691VUVEv3YfZC19+KXMeho+V2CBT9UxOITLAfQaMHJkXjwMvVWC8l/lFXaE/6PhrSedzY2Vq2IF8tV5oyqhlfiF2k8WkgCWABQSQcEGSzXLGjLDYp3dtxNNKlcKb2Bvlyhl2ARxxlYlgGz6dkwbmnXkA2PA01HcnNMnPFIZr8JCfmbCPyvT0u+3rjQ88YjO3KDUIdSCPQf3Zc3+b/S9e/wpNc+rY3gOgmNFcJy83MDffw5oscNmtQR3AOfXH8MBxUThgXtCqGkUx7Gar/Y/3jc9Am4DDgBqE2YDNkamN1O7R2IXuWntSVIsKszte4yYDvZHJ/XUBwOhx9mlu4vFfg0+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
